# Generated by Django 5.0 on 2025-09-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check1', models.CharField(max_length=200)),
                ('check2', models.IntegerField()),
                ('check3', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
