# Generated by Django 5.0 on 2025-09-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_check_delete_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_year', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Check',
        ),
    ]
