# Generated by Django 5.0 on 2025-09-16 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_delete_director_movie_likes_delete_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='likes',
        ),
        migrations.AddField(
            model_name='movie',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, help_text='Users who hid this movie', related_name='hidden_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
