# Generated by Django 5.0 on 2025-11-17 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_likes_movie_hidden_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='wishlisted_by',
            field=models.ManyToManyField(blank=True, help_text='Users who wishlisted this movie', related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
